### ISSUE TITLE
Feature: alternative triggers

### ISSUE THREAD

**Issue by IdiosApps** [kopach/espanso-package-date-utilities#3]
The documentation notes :d0 as Today
It could be useful to have :td, :tod all give the same result.

Similarly, :tm, :tom would for well for :d1 (tomorrow)

Similarly these would be great:
- :mon for (this) Monday
- :tue
- :wed
- :thu
- :fri
- :sat
- :sun

I was inspired by Todoist being aware of "Tod" being "today", for example. I think these would be quite intuitive.

**Comment by kopach** [comment]
Hi @IdiosApps, thunks for your suggestions. This feature already available since https://github.com/kopach/espanso-package-date-utilities/pull/4. Update this plugin from latest `master`


| Keyword | Description                 |
| ------- | --------------------------- |
| `:motw` | Monday this week            |
| `:tutw` | Tuesday this week           |
| `:wetw` | Wednesday this week         |
| `:thtw` | Thursday this week          |
| `:frtw` | Friday this week            |
| `:satw` | Saturday this week          |

I can't use exact shortcuts you suggest as those might overlap with others. Current version of espanso woks in a way, that it will replace first occurrence of characters. So, e.g given those shortcuts
- `:mon` - Monday
- `:monw` - Monday next week

Monday next week will newer be triggered as `:mon` is sub-string of `:monw` and will be triggered firs.
Also, I couldn't implement "current" Sunday as in some calendars Sunday is first day of the week and in other - last. User variable could help here, but I'm blocked with this defect to implement it https://github.com/federico-terzi/espanso/issues/693

**Comment by kopach** [comment]
Closing this issue as of now. Feel free to reopen it if you have any other suggestions/comments here.
